export { default as AddFeatured } from "./AddFeatured";
export { default as AddProduct } from "./AddProduct";
export { default as DashBoard } from "./DashBoard";
export {default as Alert} from "./Alert";
export { default as Categories } from "./Categories";
export { default as DisplayProducts } from "./DisplayProducts";
export { default as Featured } from "./Featured";
export { default as Footer } from "./Footer";
export { default as Hero } from "./Hero";
export { default as Login } from "./Login";
export { default as NavBar } from "./NavBar";
export { default as OfferBanner } from "./OfferBanner";
export { default as ProductSlider } from "./ProductSlider";
export { default as StatCard } from "./StatCard";
export { default as SignUp } from "./SignUp";
export {default as ViewOrUpdateFeatured} from "./ViewOrUpdateFeatured";
export {default as ViewOrUpdateProduct} from "./ViewOrUpdateProduct";
export {default as Users} from "./Users";